# Global defined variables
variables:
  SAST_DISABLE_DIND: "true"

# Execution stages
stages:
 - build
 - test
 - secure
 - deploy

# Template includes
include:
  - .gitlab/Yarn-Build.gitlab-ci.yml
  - .gitlab/Yarn-Test.gitlab-ci.yml
#   - template: Jobs/Code-Quality.gitlab-ci.yml


# =================================================
# DEPLOY
# =================================================

pages:
  stage: deploy
  variables:
    FF_USE_FASTZIP: "true"
    ARTIFACT_COMPRESSION_LEVEL: "fastest"
  dependencies: 
    - build
  script:
    - rm -rf public/*
    - mv dist_electron/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: always
    - if: '$CI_COMMIT_BRANCH == "ci"'
      when: always
