# Global defined variables
variables:
  SAST_DISABLE_DIND: "true"

# Execution stages
stages:
 - build
 - test
 - secure
 - deploy

# Template includes
include:
  - .gitlab/Yarn-Build.gitlab-ci.yml
  - .gitlab/Yarn-Test.gitlab-ci.yml
#   - template: Jobs/Code-Quality.gitlab-ci.yml


# =================================================
# DEPLOY
# =================================================

deploy_to_update_server:
  stage: deploy
  variables:
    SERVER: https://updates.sololegends.com/electron/win/upload
    APP_NAME: SL Game Launcher
  dependencies: 
    - build
  script:
    - sh upload_dist.sh
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/'
      when: always
    - if: '$CI_COMMIT_BRANCH == "ci"'
      when: always
