image: docker.sololegends.com:443/docker/nodejs:build-16-14-2

    
lint-eslint:
  stage: test
  script: 
    - yarn
    - yarn lint
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'