build:
  stage: build
  image: electronuserland/builder:16-wine
  before_script:
    - ls -la
    - wine --version
  script:
    - yarn
    - yarn exe-build-ci
    - rm -rf dist_electron/mac
    - rm -rf dist_electron/win-unpacked
    - rm -rf dist_electron/linux-unpacked
    # Build the index for pages
    - node tools/build_pages_html.js --folder=dist_electron --template=tools/templates/file_list.html --recursive
  artifacts:
    paths:
      - dist_electron
    expire_in: 1d
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: always
    - if: '$CI_COMMIT_BRANCH == "ci"'
      when: always

build-beta:
  stage: build
  image: electronuserland/builder:16-wine
  before_script:
    - ls -la
    - wine --version
  script:
    - yarn
    - yarn exe-build-ci
    - rm -rf dist_electron/mac
    - rm -rf dist_electron/win-unpacked
    - rm -rf dist_electron/linux-unpacked
    # Build the index for pages
    - node tools/build_pages_html.js --folder=dist_electron --template=tools/templates/file_list.html --recursive
  artifacts:
    paths:
      - dist_electron
    expire_in: 1d
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+$/'
      when: always
