#!/bin/bash 

echo "#===========================#"
echo "# SL Launcher Game Repacker #"
echo "#===========================#"
cd ..
echo "Building typescript project..."
npx tsc -p tsconfig.repack.json

cd tools
export SL_LAUNCHER_APP_OFF
node ../dist/tools/process_new_game.js "$@"